--- #YAML:1.0
name:                   WWW-UsePerl-Journal
version:                0.10
abstract:               Handles the retrieval of UsePerl journal comment threads..
author:
  - Barbie <barbie@cpan.org>

license:                perl
distribution_type:      module
installdirs:            site

requires:
  HTTP::Request::Common:  0
  LWP::UserAgent:         0
  Test::More:             0.47
  Time::Piece:            0
  WWW::UsePerl::Journal:  0.20
recommends:
  Test::More:             0.47
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
  Test::YAML::Valid:      0.06
build_requires:
  Test::More:             0.47

provides:
  WWW::UsePerl::Journal::Thread:
    file:     lib/WWW/UsePerl/Journal/Thread.pm
    version:  0.10
  WWW::UsePerl::Journal::Comment:
    file:     lib/WWW/UsePerl/Journal/Comment.pm
    version:  0.10
no_index:
  directory:
    - t
    - examples

meta-spec:
   version:   1.3
   url:       http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by: Hand 1.0
